kind: Simple
apiVersion: k3d.io/v1alpha4
metadata:
  name: my-cluster
image: rancher/k3s:v1.24.4-k3s1
servers: 1
agents: 2
ports:
- port: 0.0.0.0:80:80
  nodeFilters:
  - loadbalancer
- port: 0.0.0.0:8080:8080
  nodeFilters:
  - loadbalancer
- port: 0.0.0.0:8900:30080
  nodeFilters:
  - agent:0:direct
- port: 0.0.0.0:8901:30081
  nodeFilters:
  - agent:0:direct
- port: 0.0.0.0:8902:30082
  nodeFilters:
  - agent:0:direct
